### ISSUE TITLE
Diagnose failing arbitrator JIT test

### ISSUE THREAD

**Issue by ethenotethan** [Layr-Labs/nitro#9]
**Describe the bug**
https://github.com/Layr-Labs/nitro-private/blob/aa2c474591f65212d636a5eb251ba8be03e94792/arbitrator/jit/src/test.rs#L8-L23 

commented out due to wasmer dependency conflict 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hopeyen** [comment]
I uncommented the test for diagnosis but the test passed without any changes
![Screenshot 2024-08-07 at 5 45 14 PM](https://github.com/user-attachments/assets/e8f0d60e-a471-4797-9b8d-554900ecd06c)

Not sure if I'm missing anything? If not, I can make a quick PR for uncommenting the test to resolve this issue

**Comment by ethenotethan** [comment]
looks like it might've been a regression solved when we rebased to v3.0.3 :)
